# Generated by Django 3.2.8 on 2021-10-12 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Lastname')),
                ('IDKind', models.CharField(max_length=30, verbose_name='IDKind')),
                ('IDNumber', models.CharField(max_length=30, verbose_name='IDNumber')),
                ('address', models.CharField(max_length=30, verbose_name='address')),
                ('city', models.CharField(max_length=30, verbose_name='city')),
                ('country', models.CharField(max_length=30, verbose_name='country')),
                ('landline', models.CharField(max_length=30, verbose_name='landline')),
                ('mobilephone', models.CharField(max_length=30, verbose_name='mobilephone')),
                ('jobs', models.CharField(max_length=30, verbose_name='jobs')),
                ('company', models.CharField(max_length=30, verbose_name='company')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('rol', models.CharField(choices=[('AD', 'Administrador'), ('OT', 'Otorgante'), ('AP', 'Adoptante')], default='AP', max_length=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('species', models.CharField(max_length=30, verbose_name='species')),
                ('size', models.CharField(choices=[('LG', 'Large'), ('MD', 'Medium'), ('SM', 'Small')], default='MD', max_length=2)),
                ('age', models.IntegerField(max_length=2, verbose_name='age')),
                ('country', models.CharField(max_length=30, verbose_name='country')),
                ('city', models.CharField(max_length=30, verbose_name='city')),
                ('cohabitation_animals', models.BooleanField(verbose_name='cohabitation_animals')),
                ('cohabitation_kids', models.BooleanField(verbose_name='cohabitation_kids')),
                ('pathologies', models.BooleanField(verbose_name='pathologies')),
                ('diseases_drugs', models.CharField(max_length=300, verbose_name='diseases_drugs')),
                ('sterilized', models.BooleanField(verbose_name='sterilized')),
                ('vaccinated', models.BooleanField(verbose_name='vaccinated')),
                ('vaccines', models.CharField(max_length=300, verbose_name='vaccines')),
                ('deworming', models.BooleanField(verbose_name='deworming')),
                ('dewormer', models.CharField(max_length=300, verbose_name='dewormer')),
                ('history', models.CharField(max_length=400, verbose_name='history')),
                ('status', models.CharField(choices=[('RG', 'Registered'), ('RQ', 'Requested'), ('AP', 'Adopted'), ('RT', 'Registered')], default='RG', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestPet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_kind', models.CharField(choices=[('AD', 'Adoption'), ('HD', 'Handing')], max_length=2)),
                ('finalized_at', models.DateTimeField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authadoptapp.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
