# Generated by Django 3.2.8 on 2021-10-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authadoptapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('RG', 'Registered'), ('RQ', 'Requested'), ('AP', 'Adopted'), ('RT', 'Retired')], default='RG', max_length=2),
        ),
    ]
