# Generated by Django 3.2.8 on 2021-10-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authadoptapp', '0002_auto_20211020_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('RG', 'Registered'), ('RQ', 'Requested'), ('AP', 'Adopted'), ('RT', 'Registered')], default='RG', max_length=2),
        ),
        migrations.AlterField(
            model_name='requestpet',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
